window.JB_APPS = {
	"pocket-studio": {
		slug: "pocket-studio",
		packageId: "com.jebstudios.pocketstudio",
		icon: "../images/apps/pocket-studio.png",
		privacy: "../pocket-studio-privacy-policy.html",
		tags: ["Flutter", "Dart", "On-device AI"],
		en: {
			title: "Pocket Studio",
			tagline: "Product photo editor for e-commerce sellers",
			desc: "Your product photography studio in your pocket. Designed for sellers, entrepreneurs, and online stores that need professional images without desktop software or a constant internet connection.",
			features: [
				"AI background removal processed on your device",
				"Realistic clothing recoloring for catalog variants",
				"Multi-touch canvas with text, stickers, and watermarks",
				"Export presets for marketplaces, Shopify, and social formats",
				"Works offline — photos are not uploaded for editing",
			],
		},
		es: {
			title: "Pocket Studio",
			tagline: "Editor de fotos de producto para e-commerce",
			desc: "Tu estudio de fotografía de producto en el bolsillo. Pensado para vendedores, emprendedores y tiendas en línea que necesitan imágenes profesionales sin software de escritorio ni conexión constante.",
			features: [
				"Eliminación de fondo con IA procesada en el dispositivo",
				"Recolorado realista de ropa para variantes de catálogo",
				"Lienzo multitáctil con texto, stickers y marcas de agua",
				"Presets de exportación para marketplaces, Shopify y redes",
				"Funciona sin conexión — las fotos no se suben para editar",
			],
		},
	},
	"earth-defender": {
		slug: "earth-defender",
		packageId: "com.jebstudios.earth_defender",
		icon: "../images/apps/earth-defender.png",
		privacy: "../earth-defender-privacy-policy.html",
		tags: ["Flutter", "Dart", "AdMob"],
		en: {
			title: "Earth Defender",
			tagline: "Vertical space shooter with permanent progression",
			desc: "Earth is under attack. Pilot your starfighter, destroy waves of alien ships, earn coins in combat, and invest in the orbital workshop to return stronger each mission.",
			features: [
				"50 levels with epic bosses at levels 10, 20, 30, 40, and 50",
				"Drag-to-move controls with automatic fire",
				"Permanent upgrade workshop: hull, weapons, shields, drones",
				"In-combat power-ups: healing, double damage, shield, coin magnet",
				"Progress saved locally on your device",
			],
		},
		es: {
			title: "Earth Defender",
			tagline: "Shooter espacial vertical con progresión permanente",
			desc: "La Tierra está bajo ataque. Pilota tu caza, destruye oleadas de naves alienígenas, gana monedas en combate e invierte en el taller orbital para volver más fuerte en cada misión.",
			features: [
				"50 niveles con jefes épicos en los niveles 10, 20, 30, 40 y 50",
				"Controles de arrastre con disparo automático",
				"Taller orbital: mejoras permanentes de casco, armas, escudos y drones",
				"Potenciadores: curación, doble daño, escudo e imán de monedas",
				"Progreso guardado localmente en el dispositivo",
			],
		},
	},
	"mastermind-football": {
		slug: "mastermind-football",
		packageId: "com.jebstudios.mastermind_football",
		icon: "../images/apps/mastermind-football.png",
		privacy: "../mastermind-football-privacy-policy.html",
		tags: ["Flutter", "Dart", "AdMob"],
		en: {
			title: "Mastermind Football",
			tagline: "Deep football management simulator",
			desc: "A mobile football management simulator for those who enjoy making decisions off the pitch. Create your club, define its identity, and lead your team season after season.",
			features: [
				"Choose league and team; customize name, stadium, colors, and crest",
				"Up to three independent save slots",
				"Squad management, training, transfers, and scouting",
				"Live 2D matches with tactical adjustments or instant simulation",
				"Facilities upgrades: stadium, medical center, youth academy",
			],
		},
		es: {
			title: "Mastermind Football",
			tagline: "Simulador profundo de gestión futbolística",
			desc: "Simulador de gestión futbolística para quienes disfrutan decidir fuera del campo. Crea tu club, define su identidad y llévalo a la cima temporada tras temporada.",
			features: [
				"Elige liga y equipo; personaliza nombre, estadio, colores y escudo",
				"Hasta tres partidas independientes",
				"Gestión de plantilla, entrenamiento, fichajes y scouting",
				"Partidos 2D en vivo con ajustes tácticos o simulación instantánea",
				"Mejoras de instalaciones: estadio, centro médico y cantera",
			],
		},
	},
	"smart-utilities": {
		slug: "smart-utilities",
		packageId: "com.jebstudios.smart_utilities",
		icon: "../images/apps/smart-utilities.png",
		privacy: null,
		tags: ["Flutter", "Dart"],
		en: {
			title: "JEB Smart Utilities",
			tagline: "Everyday tools in one clean app",
			desc: "Practical everyday tools in a single app with a clean design and quick access from the home screen. Many features work offline on your Android device.",
			features: [
				"Flashlight, calculator, unit converter, spirit level, and compass",
				"QR and barcode scanner and generator",
				"Timer, to-do lists, reminders, sticky notes, and alarms",
				"Menstrual calendar for cycle tracking",
				"Customizable home grid and multilingual UI (ES, EN, FR, PT)",
			],
		},
		es: {
			title: "JEB Smart Utilities",
			tagline: "Herramientas cotidianas en una sola app",
			desc: "Herramientas prácticas del día a día en una sola app con diseño limpio y acceso rápido desde la pantalla principal. Muchas funciones funcionan sin conexión en Android.",
			features: [
				"Linterna, calculadora, conversor de unidades, nivel de burbuja y brújula",
				"Escáner y generador de códigos QR y barras",
				"Temporizador, listas, recordatorios, notas adhesivas y alarmas",
				"Calendario menstrual para seguimiento del ciclo",
				"Cuadrícula personalizable e interfaz multilingüe (ES, EN, FR, PT)",
			],
		},
	},
	"smart-iptv": {
		slug: "smart-iptv",
		packageId: "com.JEBStudios.smartiptv",
		icon: "../images/apps/smart-iptv.png",
		privacy: "../advertising-policy.html",
		tags: ["Flutter", "Dart", "AdMob"],
		en: {
			title: "JEB Studios Smart IPTV",
			tagline: "IPTV player for your own playlists",
			desc: "A media player to watch live TV and streams from playlists you add yourself. The app does not include pre-loaded channels — you import your own M3U/M3U8 content.",
			features: [
				"Import and manage M3U and M3U8 playlists",
				"Built-in player for live streams on phone and TV",
				"Favorites and channel organization",
				"User-provided content only — no bundled channels",
				"Privacy policy available on this site",
			],
		},
		es: {
			title: "JEB Studios Smart IPTV",
			tagline: "Reproductor IPTV para tus propias listas",
			desc: "Reproductor multimedia para ver TV en vivo y streams desde listas que tú agregas. La app no incluye canales precargados — importas tu propio contenido M3U/M3U8.",
			features: [
				"Importar y gestionar listas M3U y M3U8",
				"Reproductor integrado para streams en vivo en móvil y TV",
				"Favoritos y organización de canales",
				"Solo contenido del usuario — sin canales incluidos",
				"Política de privacidad disponible en este sitio",
			],
		},
	},
	konti: {
		slug: "konti",
		packageId: "com.jebstudios.konti",
		icon: "../images/apps/konti.svg",
		privacy: "../konti-privacy-policy.html",
		tags: ["Flutter", "Dart", "Supabase"],
		en: {
			title: "Konti",
			tagline: "Business management for micro-entrepreneurs",
			desc: "A cloud-connected business tool for small entrepreneurs in Latin America. Track cash flow, manage inventory, follow up on debts, invite your team, and export monthly reports — all from your phone.",
			features: [
				"Multi-business support with income and expense tracking",
				"Inventory with stock alerts and optional product photos",
				"Debt tracking for money to collect or to pay",
				"Team management — invite employees by email",
				"Monthly cash-flow reports with CSV export",
			],
		},
		es: {
			title: "Konti",
			tagline: "Gestión empresarial para microemprendedores",
			desc: "Herramienta empresarial en la nube para pequeños emprendedores en Latinoamérica. Controla flujo de caja, inventario, deudas, invita a tu equipo y exporta reportes mensuales desde tu teléfono.",
			features: [
				"Soporte multi-negocio con registro de ingresos y gastos",
				"Inventario con alertas de stock y fotos de producto opcionales",
				"Seguimiento de deudas por cobrar o por pagar",
				"Gestión de equipo — invita empleados por correo",
				"Reportes mensuales de flujo de caja con exportación CSV",
			],
		},
	},
	glowpulse: {
		slug: "glowpulse",
		packageId: "com.jebstudios.glowpulse",
		icon: "../images/apps/glowpulse.svg",
		privacy: "../glowpulse-privacy-policy.html",
		tags: ["Flutter", "Dart", "Offline"],
		en: {
			title: "GlowPulse",
			tagline: "Synthwave Tetris-style puzzle game",
			desc: "A classic Tetris-style puzzle game with a synthwave neon aesthetic. Fully offline — no account, no ads, no analytics. All gameplay runs on your device.",
			features: [
				"Block-stacking puzzle with neon synthwave visuals",
				"High score and audio preference saved locally",
				"No account or internet required",
				"No advertisements or third-party tracking",
				"Uninstalling removes all local data",
			],
		},
		es: {
			title: "GlowPulse",
			tagline: "Puzzle estilo Tetris con estética synthwave",
			desc: "Juego de puzzle clásico estilo Tetris con estética synthwave neón. Totalmente sin conexión — sin cuenta, sin anuncios, sin analíticas. Todo el juego corre en tu dispositivo.",
			features: [
				"Puzzle de bloques con visuales synthwave neón",
				"Puntuación alta y preferencia de audio guardadas localmente",
				"Sin cuenta ni internet requeridos",
				"Sin anuncios ni rastreo de terceros",
				"Desinstalar elimina todos los datos locales",
			],
		},
	},
};
